AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AppPrefix:
    Type: "String"
    Default: "opm"
    AllowedValues:
      - "opm"
  EnvPrefix:
    Type: "String"
    Default: "stg"
    AllowedValues:
      - "stg"
      - "prod"

Resources:
  TerraformBackendStateLockTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub
        - "${app}-${env}-dynamodb-terrafromremotebackend"
        - app: !Ref AppPrefix
          env: !Ref EnvPrefix
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
