AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AppPrefix:
    Type: "String"
    Default: "opm"
    AllowedValues:
      - "opm"
  EnvPrefix:
    Type: "String"
    Default: "stg"
    AllowedValues:
      - "stg"
      - "prod"

Resources:
  IamuserAdmincli:
    Type: "AWS::IAM::User"
    Properties:
      Path: /
      UserName: !Sub
        - "${app}-${env}-user-admincli"
        - app: !Ref AppPrefix
          env: !Ref EnvPrefix
      Groups:
        - Fn::ImportValue: !Sub
            - "${app}-${env}-${name}"
            - app: !Ref AppPrefix
              env: !Ref EnvPrefix
              name: Admincli
